In [ ]:
Matrix and their basic operation

In [11]:
x=[1,2,3,4,5]

In [12]:
import  numpy as np
X=np.array([1,2,3,4,5])
print(X)
print(type(x))

[1 2 3 4 5]
<class 'list'>


In [23]:
m=np.array([[1,2,3],
          [4,5,6],
          [7,8,0]])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [24]:
print('Matrix transpose:\n',m.transpose(),'\n')
print('Matrix determinant:\n',np.linalg.det(m),'\n')
m_inv=np.linalg.inv(m)
print('Matrix Inverse:\n',m_inv,'\n')
iden_m=np.dot(m,m_inv)
iden_m=np.round(np.abs(iden_m),0)
print('Product of matrix and its inverse:\n',iden_m)

Matrix transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 0]] 

Matrix determinant:
 27.0 

Matrix Inverse:
 [[-1.77777778  0.88888889 -0.11111111]
 [ 1.55555556 -0.77777778  0.22222222]
 [-0.11111111  0.22222222 -0.11111111]] 

Product of matrix and its inverse:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
eigen_vals,eigen_vecs=np.linalg.eig(m)
print('Eigen values',eigen_vals,'\n')
print('Eigen vector:\n',eigen_vecs)

Eigen values [-1.79244726 11.54204466  7.2504026 ] 

Eigen vector:
 [[ 0.8690616  -0.34185355 -0.01965159]
 [-0.49420916 -0.37632122 -0.39239997]
 [ 0.02211857 -0.86111468  0.91958473]]


In [25]:
U,S,VT=np.linalg.svd(m)
print('getting svd outputs:-\n')
print('U:\n',U,'\n')
print('S:\n',S,'\n')
print('VT:\n',VT,'\n')

getting svd outputs:-

U:
 [[-0.23035703 -0.39607121 -0.88885501]
 [-0.60728383 -0.65520761  0.44934322]
 [-0.76035649  0.64329665 -0.08959596]] 

S:
 [13.20145862  5.43875711  0.37604705] 

VT:
 [[-0.60462923 -0.72567626 -0.32835569]
 [ 0.27325634  0.19824248 -0.94129214]
 [ 0.74816741 -0.65885802  0.07843244]] 



In [29]:
zeros_array=np.zeros((2,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
ones_array=np.ones((1,5))
print(ones_array)

[[1. 1. 1. 1. 1.]]


In [31]:
import scipy as sp
import numpy as np

In [37]:
nums=np.random.randint(1,20, size=(1,15))[0]
print('Data: ',nums)

Data:  [ 6 14 13  5 16  7  5 17  8  8 17 10 19  8  4]


In [50]:
print('Mean:',np.mean(nums))
print('Median:',np.median(nums))
print('Mode:',sp.stats.mode(nums))
print('Standard division:',np.std(nums))
print('Variance:',np.var(nums))
print('Skew:',sp.stats.skew(nums))
print('Kurtosis:',sp.stats.kurtosis(nums))

Mean: 10.466666666666667
Median: 8.0
Mode: ModeResult(mode=array([8]), count=array([3]))
Standard division: 4.8971647125885225
Variance: 23.982222222222223
Skew: 0.36093460567830765
Kurtosis: -1.346008986696897


C:\Users\User\AppData\Local\Temp\ipykernel_10468\1043519277.py:3: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print('Mode:',sp.stats.mode(nums))


In [51]:
#ex01
#write a code to generate 3 random integers between 100 and 999 which is divisible by 5

In [52]:
#ex02
#write a code to generate 100 random lottery tickets and pick two lucky tickets from it as a winner.
#the lottery must be 10 digits long.
#all 100 ticket number must be unique.
#generate a random list of 1000 numbers using randarange() and then use the sample() method to pick lucky 2 tickets

In [ ]:
#ex03
#write a code to generate a random password which meets the following condition.
#password length must be 10 characters long
#it must contain at least 2 uppercase